### PR TITLE
add fructure description

### LINKED ISSUE #15: Describe Fructure
@disconcision could you fill description for Fructure for this list? 🙏

### PR DESCRIPTION
**Pull request by disconcision**
closes #15

### CODE REVIEW

**Comment by yairchu** [comment]
Several comments to fit the style of other descriptions:

> A structured interaction engine using a rewriting DSL to model both language- and editor-level concepts

If I understand correctly the part starting with "using a rewriting DSL..." is an explanation of its inner workings, rather than what the user-facing product. I left the resolution of inner working at just the implementation language (which I hope might be useful to let projects finding possible opportunities for sharing code and find like-minded groups etc).

So dropping it would leave us at:

> A structured interaction engine

What do you mean by "engine"? A framework to create structural editors, like MPS? If so, then the term more people in the space might be familiar with would probably be a language workbench.

**Comment by disconcision** [comment]
hmm, so it depends on where I draw the line between aspiration/actuality and at what level the 'users' live. when working on fructure I was very much thinking about the 'users' as being both end-users and language-implementors in the Racket Language-Oriented-Programming tradition, hence the emphasis on DSL ergonomics and a unified interface for language transformations and editor actions (which I mentioned as AFAICT this aspect is unique to fructure). If it was intended to be soley inner-workings my implementation approach would have been very different, and I wouldn't have bothered will ancilliary libraries like [containment-patterns](https://github.com/disconcision/containment-patterns). The current implementation doesn't fully succeed at this goal though. So in this sense 'language workbench' would be accurate, yes.

**Comment by disconcision** [comment]
maybe "A language workbench in the Racket Language-Oriented Programming tradition?"

**Comment by yairchu** [comment]
That sounds good.

And excuse my ignorance but is it fair to say that Racket itself is a sort of language workbench?

If so, is fructure aimed to work for languages implemented in Racket? Or does it replace Racket? If its the former then perhaps "A projectional editor workbench for Racket-implemented languages" would be appropriate?

**Pull request merged**
